stop-words = "../data/lemur-stopwords.txt"
libsvm-modules = "../deps/libsvm-modules/"
prefix = "../data/"
function-words = "../data/function-words.txt"
punctuation = "../data/sentence-boundaries/sentence-punctuation.txt"
start-exceptions = "../data/sentence-boundaries/sentence-start-exceptions.txt"
end-exceptions = "../data/sentence-boundaries/sentence-end-exceptions.txt"
query-judgements = "../data/ceeaus-qrels.txt"
query-path = "../queries.txt" # create this file

dataset = "20newsgroups"
corpus = "line.toml" # located inside dataset folder
forward-index = "20news-fwd"
inverted-index = "20news-inv"
indexer-ram-budget = 1024 # **estimated** RAM budget for indexing in MB
                          # always set this lower than your physical RAM!

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-chain"

[ranker]
method = "bm25"
k1 = 1.2
b = 0.75
k3 = 500
