stop-words = "../meta/data/lemur-stopwords.txt"
prefix = "../meta/data/"
function-words = "../meta/data/function-words.txt"
punctuation = "../meta/data/sentence-boundaries/sentence-punctuation.txt"
start-exceptions = "../meta/data/sentence-boundaries/sentence-start-exceptions.txt"
end-exceptions = "../meta/data/sentence-boundaries/sentence-end-exceptions.txt"
query-judgements = "../meta/data/ceeaus-qrels.txt"
query-path = "../queries.txt" # create this file

dataset = "ceeaus"
corpus-type = "line-corpus" # for MeTA < v2.0
corpus = "line.toml" # located inside dataset folder, for MeTA >= v2.0
forward-index = "ceeaus-fwd"
inverted-index = "ceeaus-inv"
indexer-ram-budget = 1024 # **estimated** RAM budget for indexing in MB
                          # always set this lower than your physical RAM!
                          # for MeTA >= v2.0

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-chain"

[ranker]
method = "bm25"
k1 = 1.2
b = 0.75
k3 = 500
